### ISSUE TITLE
TypeError: nonzero() got an unexpected keyword argument 'as_tuple'

### ISSUE THREAD

**Issue by Carmenvanveen** [makcedward/nlpaug#147]
After running 
"Substitute word by contextual word embeddings (BERT, DistilBERT, RoBERTA or XLNet)" I get the following error: 

2020-09-17 10:45:19.186595: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForMaskedLM were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['cls.predictions.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "C:/Users/Carmen_TU/Thesis/Snorkel-Augmentation/test_files/augment_test.py", line 26, in <module>
    augmented_text = aug.augment(text)
  File "C:\Users\Carmen_TU\anaconda3\envs\Snorkel_Env\lib\site-packages\nlpaug\base_augmenter.py", line 86, in augment
    augmented_results = [action_fx(clean_data) for _ in range(n)]
  File "C:\Users\Carmen_TU\anaconda3\envs\Snorkel_Env\lib\site-packages\nlpaug\base_augmenter.py", line 86, in <listcomp>
    augmented_results = [action_fx(clean_data) for _ in range(n)]
  File "C:\Users\Carmen_TU\anaconda3\envs\Snorkel_Env\lib\site-packages\nlpaug\augmenter\word\context_word_embs.py", line 282, in substitute
    outputs = self.model.predict(masked_text, target_word=original_word, n=1+_)
  File "C:\Users\Carmen_TU\anaconda3\envs\Snorkel_Env\lib\site-packages\nlpaug\model\lang_models\bert.py", line 71, in predict
    results = self.pick(target_token_logits, target_token_idxes, target_word=target_word, n=n)
  File "C:\Users\Carmen_TU\anaconda3\envs\Snorkel_Env\lib\site-packages\nlpaug\model\lang_models\language_models.py", line 90, in pick
    candidate_ids, candidate_probas = self.prob_multinomial(logits, n=n*10)
  File "C:\Users\Carmen_TU\anaconda3\envs\Snorkel_Env\lib\site-packages\nlpaug\model\lang_models\language_models.py", line 104, in prob_multinomial
    num_sample = min(n, torch.nonzero(probas, as_tuple=False).size(0))  # Number of potential candidate is small when top_k/ top_p are used.
TypeError: nonzero() got an unexpected keyword argument 'as_tuple'

Somebody has an idea?

**Comment by jieruyao49** [comment]
i meet same question, how to solve it?
