### ISSUE TITLE
Cuda out of memory using bert with gpu: RuntimeError: CUDA out of memory. Tried to allocate 11.76 GiB (GPU 0; 14.76 GiB total capacity; 1.00 GiB already allocated; 1.23 GiB free; 12.60 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by randywreed** [makcedward/nlpaug#204]
Love this package, just started trying to use it with a GCP GPU (T4,14GB). Got this error trying to use the bert substitution augmentation.

Error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/spell/left_out_aug_apply.py", line 169, in <module>
    newaugs_df=run_augmentation(augs,newaugs,df,nodisp,bs)
  File "/spell/left_out_aug_apply.py", line 118, in run_augmentation
    aug_out=aug.augment(new_df_list)
  File "/usr/local/lib/python3.7/dist-packages/nlpaug/flow/pipeline.py", line 58, in augment
    augmented_results = [self._augment(data) for _ in range(n)]
  File "/usr/local/lib/python3.7/dist-packages/nlpaug/flow/pipeline.py", line 58, in <listcomp>
    augmented_results = [self._augment(data) for _ in range(n)]
  File "/usr/local/lib/python3.7/dist-packages/nlpaug/flow/pipeline.py", line 103, in _augment
    augmented_data = aug.augment(augmented_data, n=n, num_thread=num_thread)
  File "/usr/local/lib/python3.7/dist-packages/nlpaug/base_augmenter.py", line 95, in augment
    result = action_fx(clean_data)
  File "/usr/local/lib/python3.7/dist-packages/nlpaug/augmenter/word/context_word_embs.py", line 250, in insert
    outputs = self.model.predict(masked_texts, target_words=None, n=2)
  File "/usr/local/lib/python3.7/dist-packages/nlpaug/model/lang_models/bert.py", line 89, in predict
    outputs = self.model(input_ids=token_inputs, token_type_ids=segment_inputs, attention_mask=mask_inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py", line 1311, in forward
    prediction_scores = self.cls(sequence_output)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py", line 659, in forward
    prediction_scores = self.predictions(sequence_output)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py", line 649, in forward
    hidden_states = self.decoder(hidden_states)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA out of memory. Tried to allocate 11.76 GiB (GPU 0; 14.76 GiB total capacity; 1.00 GiB already allocated; 1.23 GiB free; 12.60 GiB reserved in total by PyTorch)
```
Code:
```
func_dict={"keyboard_aug":{"method":"nac.KeyboardAug","args":{}},
  "spelling_aug":{"method":"naw.SpellingAug","args":{}},
  "word2vec_aug":{"method":"naw.WordEmbsAug","args":{"model_type":"word2vec","model_path":"GoogleNews-vectors-negative300.bin","action":"substitute"}},
  "bert_sub_aug":{"method":"naw.ContextualWordEmbsAug","args":{"model_path":"bert-base-uncased","model_type":"bert","action":"substitute"}},
  "bert_ins_aug":{"method":"naw.ContextualWordEmbsAug","args":{"model_path":"bert-base-uncased","model_type":"bert","action":"insert"}},
  "xlnet_sub_aug":{"method":"naw.ContextualWordEmbsAug","args":{"model_path":"xlnet-base-cased","model_type":"xlnet","action":"substitute"}}
} 
new_df_list=new_df['text'].tolist()
new_df_label=new_df['label'].tolist()
new_method=func_dict[a]['method']
meth_args=func_dict[a]['args']
if args.gpu:
      meth_args['device']="cuda"
if args.skip:
      meth_args['stopwords']=args.skip.split(',')
m_pieces=new_method.split(".")
m=globals()[m_pieces[0]]
func=getattr(m,m_pieces[1])
aug=nafc.Sequential(func(**meth_args))
aug_out=aug.augment(new_df_list)
```

**Comment by randywreed** [comment]
A little more information about this error. This seems to happen if I send the augmented a list, If I just give it one text at a time, it does not error.

**Comment by makcedward** [comment]
what is the size of the list? it seems the input is too large. Try to reduce to a size of 16. If everything ok, increase it by times 2 to find the optimal value. Will implement batch size to automate the process

**Comment by makcedward** [comment]
Batch process is supported from 1.1.5 release
