### ISSUE TITLE
TypeError: tokens: expected a list of strings, got a string

### ISSUE THREAD

**Issue by yohskar** [makcedward/nlpaug#218]
The error shows up the second time nlpaug is used ... 

> import nlpaug.augmenter.word as naw
> aug = naw.SynonymAug(aug_src='wordnet') 

I got the error .... : 

>>> import nlpaug.augmenter.word as naw
>>> aug = naw.SynonymAug(aug_src='wordnet') 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/acosas/env_38a/lib/python3.8/site-packages/nlpaug/augmenter/word/synonym.py", line 64, in __init__
    self.model = self.get_model(aug_src, lang, model_path, force_reload)
  File "/home/user/acosas/env_38a/lib/python3.8/site-packages/nlpaug/augmenter/word/synonym.py", line 161, in get_model
    return nmw.WordNet(lang=lang, is_synonym=True)
  File "/home/user/acosas/env_38a/lib/python3.8/site-packages/nlpaug/model/word_dict/wordnet.py", line 28, in __init__
    nltk.pos_tag('computer')
  File "/home/user/acosas/env_38a/lib/python3.8/site-packages/nltk/tag/__init__.py", line 165, in pos_tag
    return _pos_tag(tokens, tagset, tagger, lang)
  File "/home/user/acosas/env_38a/lib/python3.8/site-packages/nltk/tag/__init__.py", line 119, in _pos_tag
    raise TypeError('tokens: expected a list of strings, got a string')
TypeError: tokens: expected a list of strings, got a string

I use :
nlpaug 1.1.3
nltk 3.6.2

Thanks !

**Comment by makcedward** [comment]
nltk changed API interface from 3.6. Applied the fix to master branch. You may either build from master branch or downgrade nltk to 3.5 version as a short term solution
