### ISSUE TITLE
运行lambada.py出错

### ISSUE THREAD

**Issue by bairan1** [makcedward/nlpaug#291]
Error
**********************************************************************
File "/home/bair/aaa/nlpaug-master/nlpaug/augmenter/sentence/lambada.py", line 63, in LambadaAug
Failed example:
    aug = nas.LambadaAug()
Exception raised:
    Traceback (most recent call last):
      File "/home/zhuangxq/ruanjian/pycharm-community-2021.1/plugins/python-ce/helpers/pycharm/docrunner.py", line 139, in __run
        compileflags, 1), test.globs)
      File "<doctest LambadaAug[1]>", line 1, in <module>
        aug = nas.LambadaAug()
    TypeError: __init__() missing 1 required positional argument: 'model_dir'

**Comment by makcedward** [comment]
you need to train a model first. Follow this [notebook ](https://github.com/makcedward/nlpaug/blob/master/example/lambada-train_model.ipynb)to train a model and load it for inferecning.
