### ISSUE TITLE
404 Client Error: Repository Not Found for url: https://huggingface.co/fHelsinki-NLP/opus-mt-en-zh/resolve/main/config.json

### ISSUE THREAD

**Issue by hjing100** [makcedward/nlpaug#293]
back_translation_aug = naw.BackTranslationAug(
    from_model_name='Helsinki-NLP/opus-mt-zh-en',
    to_model_name='fHelsinki-NLP/opus-mt-en-zh'
)

报错：
404 Client Error: Repository Not Found for url: https://huggingface.co/fHelsinki-NLP/opus-mt-en-zh/resolve/main/config.json
Traceback (most recent call last):
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\transformers\configuration_utils.py", line 593, in _get_config_dict
    user_agent=user_agent,
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\transformers\file_utils.py", line 1854, in cached_path
    local_files_only=local_files_only,
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\transformers\file_utils.py", line 2050, in get_from_cache
    _raise_for_status(r)
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\transformers\file_utils.py", line 1971, in _raise_for_status
    raise RepositoryNotFoundError(f"404 Client Error: Repository Not Found for url: {request.url}")
transformers.file_utils.RepositoryNotFoundError: 404 Client Error: Repository Not Found for url: https://huggingface.co/fHelsinki-NLP/opus-mt-en-zh/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/python_project/28-19Knowledge_Graph_of_zhuxian/08NER_and_RelationExtraction/RelationExtraction/data_prepare/data_augmentation_code/test_nlpaug.py", line 13, in <module>
    to_model_name='fHelsinki-NLP/opus-mt-en-zh'
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\nlpaug\augmenter\word\back_translation.py", line 63, in __init__
    device=device, batch_size=batch_size, max_length=max_length
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\nlpaug\augmenter\word\back_translation.py", line 78, in get_model
    force_reload, batch_size, max_length)
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\nlpaug\augmenter\word\back_translation.py", line 27, in init_back_translatoin_model
    device=device, batch_size=batch_size, max_length=max_length)
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\nlpaug\model\lang_models\machine_translation_transformers.py", line 26, in __init__
    self.tgt_model = AutoModelForSeq2SeqLM.from_pretrained(self.tgt_model_name)
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\transformers\models\auto\auto_factory.py", line 425, in from_pretrained
    pretrained_model_name_or_path, return_unused_kwargs=True, trust_remote_code=trust_remote_code, **kwargs
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\transformers\models\auto\configuration_auto.py", line 612, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\transformers\configuration_utils.py", line 537, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\transformers\configuration_utils.py", line 599, in _get_config_dict
    f"{pretrained_model_name_or_path} is not a local folder and is not a valid model identifier listed on "
OSError: fHelsinki-NLP/opus-mt-en-zh is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Comment by makcedward** [comment]
Your model name is incorrect (you used **fHelsinki**-NLP/opus-mt-en-zh instead of **Helsinki**-NLP/opus-mt-en-zh, you should use 

```
back_translation_aug = naw.BackTranslationAug(
    from_model_name='Helsinki-NLP/opus-mt-zh-en',
    to_model_name='Helsinki-NLP/opus-mt-en-zh'
)
```
